# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Okta.OktaVerify
PackageVersion: 7.0.1.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- ProductCode: '{9A601EEB-7714-4E42-AA3E-A046866CF2F5}'
  DisplayName: OktaVerify-x64-7.0.1.0
  DisplayVersion: 7.0.1.0
  Publisher: Okta, Inc.
Installers:
- Architecture: x64
  InstallerUrl: https://ok1static2.oktacdn.com/artifacts/WINDOWS_OKTA_VERIFY/7.0.1.0/OktaVerifySetup-7.0.1.0-15bb87b.exe
  InstallerSha256: F1FE7E154E5AC84AE6034B55C91FA627312C01D9B58041C2076BADACF58AADD2
ManifestType: installer
ManifestVersion: 1.12.0
